// Generated by CoffeeScript 1.7.1
(function() {

  new App.Router();
  Backbone.history.start();

  App.topics = new App.Collections.Topics();

  App.topics.fetch().then(function() {
    return new App.Views.MainForm({
      collection: App.topics
    });
  });

}).call(this);
