// Generated by CoffeeScript 1.7.1
(function() {
  $(document).ready(function() {
    new App.Router();
    Backbone.history.start();
    return new window.App.Views.MainForm();
  });

}).call(this);
