// Generated by CoffeeScript 2.0.0-beta8
$(document).ready(function () {
  var columns, grid, paginator;
  new App.Router;
  Backbone.history.start({
    pushState: true,
    root: '/'
  });
  columns = [
    {
      name: 'id',
      label: '\u041d\u043e\u043c\u0435\u0440',
      editable: false,
      cell: Backgrid.IntegerCell.extend({ orderSeparator: '' })
    },
    {
      name: 'message',
      cell: 'string',
      label: '\u0421\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u0435'
    }
  ];
  App.messages = new App.Collections.Messages;
  grid = new Backgrid.Grid({
    columns: columns,
    collection: App.messages
  });
  paginator = new Backgrid.Extension.Paginator({ collection: App.messages });
  $('#grid').append(grid.render().$el);
  $('#paginator').append(paginator.render().$el);
  return App.messages.fetch({ reset: true });
});
