// Generated by CoffeeScript 1.7.1
(function() {
  $(document).ready(function() {
    new App.Router();
    Backbone.history.start({
      pushState: true,
      root: '/'
    });
    return new window.App.Views.TopicForm();
  });

}).call(this);
