// Generated by CoffeeScript 2.0.0-beta8
window.App = {
  Models: {},
  Views: {},
  Collections: {},
  Controllers: {},
  router: {}
};
window.vent = _.extend({}, Backbone.Events);
window.App.template = function (id) {
  if ($('#' + id).length > 0) {
    return Handlebars.compile($('#' + id).html());
  } else {
    return null;
  }
};
