// Generated by CoffeeScript 2.0.0-beta8
window.App.Collections.Topics = function (super$) {
  extends$(Topics, super$);
  function Topics() {
    super$.apply(this, arguments);
  }
  Topics.prototype.model = window.App.Models.Topic;
  Topics.prototype.url = '/topic/all';
  return Topics;
}(Backbone.Collection);
window.App.Collections.Messages = function (super$1) {
  extends$(Messages, super$1);
  function Messages() {
    super$1.apply(this, arguments);
  }
  Messages.prototype.model = window.App.Models.Message;
  Messages.getCurrentTopicId = function () {
    var cache$, close, content, open, size$;
    cache$ = document.URL.split('/');
    open = cache$[0];
    size$ = cache$.length;
    content = size$ > 2 ? [].slice.call(cache$, 1, size$ - 1) : [];
    close = cache$[size$ - 1];
    return close;
  };
  Messages.prototype.url = '/topic/messages/' + Messages.getCurrentTopicId();
  return Messages;
}(Backbone.Collection);
function isOwn$(o, p) {
  return {}.hasOwnProperty.call(o, p);
}
function extends$(child, parent) {
  for (var key in parent)
    if (isOwn$(parent, key))
      child[key] = parent[key];
  function ctor() {
    this.constructor = child;
  }
  ctor.prototype = parent.prototype;
  child.prototype = new ctor;
  child.__super__ = parent.prototype;
  return child;
}
