// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.App.Collections.Topics = (function(_super) {
    __extends(Topics, _super);

    function Topics() {
      return Topics.__super__.constructor.apply(this, arguments);
    }

    Topics.prototype.model = window.App.Models.Topic;

    Topics.prototype.url = '/topics';

    return Topics;

  })(Backbone.Collection);

  window.App.Collections.Messages = (function(_super) {
    __extends(Messages, _super);

    function Messages() {
      return Messages.__super__.constructor.apply(this, arguments);
    }

    Messages.getCurrentTopicId = function() {
      return $('#topicId').val();
    };

    Messages.prototype.url = '/topic/messages/' + Messages.getCurrentTopicId();

    Messages.prototype.state = {
      pageSize: 5,
      sortKey: "updated",
      order: 1
    };

    Messages.prototype.queryParams = {
      totalPages: null,
      totalRecords: null,
      sortKey: "sort"
    };

    Messages.prototype.parseState = function(resp, queryParams, state, options) {
      return {
        totalRecords: resp.items.length
      };
    };

    Messages.prototype.parseRecords = function(resp, options) {
      return resp.items;
    };

    return Messages;

  })(Backbone.PageableCollection);

}).call(this);
