// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __slice = [].slice;

  window.App.Collections.Topics = (function(_super) {
    __extends(Topics, _super);

    function Topics() {
      return Topics.__super__.constructor.apply(this, arguments);
    }

    Topics.prototype.model = window.App.Models.Topic;

    Topics.prototype.url = '/topics';

    return Topics;

  })(Backbone.Collection);

  window.App.Collections.Messages = (function(_super) {
    __extends(Messages, _super);

    function Messages() {
      return Messages.__super__.constructor.apply(this, arguments);
    }

    Messages.prototype.model = window.App.Models.Message;

    Messages.getCurrentTopicId = function() {
      var close, content, open, _i, _ref;
      _ref = document.URL.split("/"), open = _ref[0], content = 3 <= _ref.length ? __slice.call(_ref, 1, _i = _ref.length - 1) : (_i = 1, []), close = _ref[_i++];
      return close;
    };

    Messages.prototype.url = '/topic/messages/' + Messages.getCurrentTopicId();

    return Messages;

  })(Backbone.Collection);

}).call(this);
