// Generated by CoffeeScript 2.0.0-beta8
window.App.Models.Topic = function (super$) {
  extends$(Topic, super$);
  function Topic() {
    super$.apply(this, arguments);
  }
  Topic.prototype.validate = function (attrs) {
    if (!attrs.description)
      return '\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u043e\u0431\u044f\u0437\u0430\u0442\u0435\u043b\u044c\u043d\u043e \u0434\u043b\u044f \u0437\u0430\u043f\u043e\u043b\u043d\u0435\u043d\u0438\u044f';
  };
  Topic.prototype.initialize = function () {
    return this.bind('invalid', function (model, msg) {
      return alert(msg);
    });
  };
  return Topic;
}(Backbone.Model);
window.App.Models.Message = function (super$1) {
  extends$(Message, super$1);
  function Message() {
    super$1.apply(this, arguments);
  }
  Message.prototype.validate = function (attrs) {
    if (!attrs.message)
      return '\u0421\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u0435 \u043e\u0431\u044f\u0437\u0430\u0442\u0435\u043b\u044c\u043d\u043e \u0434\u043b\u044f \u0437\u0430\u043f\u043e\u043b\u043d\u0435\u043d\u0438\u044f';
  };
  Message.prototype.initialize = function () {
    return this.bind('invalid', function (model, msg) {
      return alert(msg);
    });
  };
  return Message;
}(Backbone.Model);
function isOwn$(o, p) {
  return {}.hasOwnProperty.call(o, p);
}
function extends$(child, parent) {
  for (var key in parent)
    if (isOwn$(parent, key))
      child[key] = parent[key];
  function ctor() {
    this.constructor = child;
  }
  ctor.prototype = parent.prototype;
  child.prototype = new ctor;
  child.__super__ = parent.prototype;
  return child;
}
