// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.App.Models.Topic = (function(_super) {
    __extends(Topic, _super);

    function Topic() {
      return Topic.__super__.constructor.apply(this, arguments);
    }

    return Topic;

  })(Backbone.Model);

  window.App.Models.Message = (function(_super) {
    __extends(Message, _super);

    function Message() {
      return Message.__super__.constructor.apply(this, arguments);
    }

    return Message;

  })(Backbone.Model);

}).call(this);
