// Generated by CoffeeScript 1.7.1

/*
Main view
 */

(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  window.App.Views.MainForm = (function(_super) {
    __extends(MainForm, _super);

    function MainForm() {
      return MainForm.__super__.constructor.apply(this, arguments);
    }

    MainForm.prototype.initialize = function() {
      var allTopics, topicForm;
      topicForm = new window.App.Views.AddTopic({
        collection: window.App.topics
      }).render();
      allTopics = new window.App.Views.TopicsView({
        collection: window.App.topics
      }).render();
      return $("#topicsTable").append(allTopics.el);
    };

    return MainForm;

  })(Backbone.View);


  /*
  Topics table
   */

  window.App.Views.TopicsView = (function(_super) {
    __extends(TopicsView, _super);

    function TopicsView() {
      return TopicsView.__super__.constructor.apply(this, arguments);
    }

    TopicsView.prototype.initialize = function() {
      ({
        initialize: function() {}
      });
      return this.collection.on('add', this.addOne, this);
    };

    TopicsView.prototype.tagName = 'tbody';

    TopicsView.prototype.render = function() {
      this.collection.each(this.addOne, this);
      return this;
    };

    TopicsView.prototype.addOne = function(topic) {
      var viewTopic;
      viewTopic = new window.App.Views.Topic({
        model: topic
      });
      return this.$el.append(viewTopic.render().el);
    };

    return TopicsView;

  })(Backbone.View);


  /*
  Add topic form
   */

  window.App.Views.AddTopic = (function(_super) {
    __extends(AddTopic, _super);

    function AddTopic() {
      return AddTopic.__super__.constructor.apply(this, arguments);
    }

    AddTopic.prototype.initialize = function() {
      return this.descriptionEl = this.$('#description');
    };

    AddTopic.prototype.el = '#topicForm';

    AddTopic.prototype.events = {
      submit: 'addTopic'
    };

    AddTopic.prototype.addTopic = function(e) {
      e.preventDefault();
      this.collection.create({
        description: this.descriptionEl.val()
      }, {
        wait: true
      });
      return this.clearForm();
    };

    AddTopic.prototype.clearForm = function() {
      return this.descriptionEl.val('');
    };

    return AddTopic;

  })(Backbone.View);


  /*
  Topic row
   */

  window.App.Views.Topic = (function(_super) {
    __extends(Topic, _super);

    function Topic() {
      return Topic.__super__.constructor.apply(this, arguments);
    }

    Topic.prototype.initialize = function() {
      return this.model.on('destroy', this.unrender, this);
    };

    Topic.prototype.tagName = 'tr';

    Topic.prototype.events = {
      'click a.delete': 'removeModel'
    };

    Topic.prototype.removeModel = function() {
      return this.model.destroy();
    };

    Topic.prototype.unrender = function() {
      return this.remove();
    };

    Topic.prototype.template = window.App.template('topicTemplate');

    Topic.prototype.render = function() {
      this.$el.html(this.template(this.model.toJSON()));
      return this;
    };

    return Topic;

  })(Backbone.View);


  /*----------------------------------------------------------------------------------------------------------------- */


  /*----------------------------------------------------------------------------------------------------------------- */


  /*
  Topic view
   */

  window.App.Views.TopicForm = (function(_super) {
    __extends(TopicForm, _super);

    function TopicForm() {
      return TopicForm.__super__.constructor.apply(this, arguments);
    }

    TopicForm.prototype.initialize = function() {
      var addMessage, allMessages;
      addMessage = new window.App.Views.AddMessage({
        collection: window.App.messages
      });
      allMessages = new window.App.Views.MessagesView({
        collection: window.App.messages
      }).render();
      return $("#messagesTable").append(allMessages.el);
    };

    return TopicForm;

  })(Backbone.Model);


  /*
  Message table
   */

  window.App.Views.MessagesView = (function(_super) {
    __extends(MessagesView, _super);

    function MessagesView() {
      return MessagesView.__super__.constructor.apply(this, arguments);
    }

    MessagesView.prototype.initialize = function() {
      return this.collection.on('add', this.addOne, this);
    };

    MessagesView.prototype.tagName = 'tbody';

    MessagesView.prototype.render = function() {
      this.collection.each(this.addOne, this);
      return this;
    };

    MessagesView.prototype.addOne = function(message) {
      var viewMessage;
      viewMessage = new window.App.Views.Message({
        model: message
      });
      return this.$el.append(viewMessage.render().el);
    };

    return MessagesView;

  })(Backbone.View);


  /*
  Add message form
   */

  window.App.Views.AddMessage = (function(_super) {
    __extends(AddMessage, _super);

    function AddMessage() {
      this.errSh = __bind(this.errSh, this);
      return AddMessage.__super__.constructor.apply(this, arguments);
    }

    AddMessage.prototype.initialize = function() {
      return this.messageEl = this.$('#message');
    };

    AddMessage.prototype.el = '#messageForm';

    AddMessage.prototype.events = {
      submit: 'addMessage'
    };

    AddMessage.prototype.addMessage = function(e) {
      e.preventDefault();
      this.collection.create({
        message: this.messageEl.val()
      }, {
        wait: true
      });
      return this.clearForm();
    };

    AddMessage.prototype.clearForm = function() {
      return this.messageEl.val('');
    };

    AddMessage.prototype.errSh = function(view, attr, error, selector) {
      return alert("fook");
    };

    return AddMessage;

  })(Backbone.View);


  /*
  Message row
   */

  window.App.Views.Message = (function(_super) {
    __extends(Message, _super);

    function Message() {
      return Message.__super__.constructor.apply(this, arguments);
    }

    Message.prototype.initialize = function() {
      return this.model.on('destroy', this.unrender, this);
    };

    Message.prototype.tagName = 'tr';

    Message.prototype.events = {
      'click a.delete': 'removeModel'
    };

    Message.prototype.removeModel = function() {
      return this.model.destroy();
    };

    Message.prototype.unrender = function() {
      return this.remove();
    };

    Message.prototype.template = window.App.template('messageTemplate');

    Message.prototype.render = function() {
      this.$el.html(this.template(this.model.toJSON()));
      return this;
    };

    return Message;

  })(Backbone.View);

}).call(this);
